using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Noggog;
using Mutagen.Bethesda.Plugins.Cache;

namespace NorthernRoadsGrassRemover
{
    public class Program
    {
        static Lazy<Settings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "NorthernRoadsGrassRemover.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (!state.LoadOrder.TryGetValue("Northern Roads.esp", out var northernRoads) || northernRoads.Mod is null)
            {
                Console.Error.WriteLine("'Northern Roads.esp' cannot be found. Make sure you have installed Northern Roads.");
                return;
            }


            var loadOrderLinkCache = state.LoadOrder.ToImmutableLinkCache();
            var northernRoadsLinkCache = northernRoads.Mod.ToImmutableLinkCache();

            // Generate Landscape Texture records without grass, based on the ones defined in TexturesToClean
            GenerateCleanLandscapeTextures(loadOrderLinkCache, state.PatchMod);

            // Iterate through cells
            foreach (var cellContext in state.LoadOrder.PriorityOrder.Cell().WinningContextOverrides(loadOrderLinkCache))
            {
                // Make sure the cell is exterior
                if (!cellContext.TryGetParent<IWorldspaceGetter>(out _)) continue;

                // If there are, replace all Landscape Texture records in that cell that are in TexturesToClean with a new Landscape Texture record with no grass
                Console.WriteLine(HasNorthernRoadsTextures(cellContext.Record, loadOrderLinkCache, northernRoadsLinkCache));
            }
        }

        public static bool HasNorthernRoadsTextures(
            ICellGetter cell,
            ILinkCache<ISkyrimMod, ISkyrimModGetter> loadOrderLinkCache,
            ILinkCache<ISkyrimMod, ISkyrimModGetter> northernRoadsLinkCache
        )
        {
            foreach (var previous in cell
                .ToLinkGetter()
                .ResolveAllContexts<ISkyrimMod, ISkyrimModGetter, ICell, ICellGetter>(loadOrderLinkCache))
            {
                var landscape = previous.Record.Landscape;
                if (landscape == null) continue;

                foreach (var layer in landscape.Layers)
                {
                    if (layer.Header == null) continue;

                    // Check for Northern Roads Landscape Texture records in the cell
                    if (northernRoadsLinkCache.TryResolve<ILandscapeTextureGetter>(layer.Header.Texture.FormKey, out var landscapeRecord)) return true;
                }
            }

            return false;
        }

        public static Dictionary<String, LandscapeTexture> GenerateCleanLandscapeTextures(
            ILinkCache<ISkyrimMod, ISkyrimModGetter> loadOrderLinkCache,
            ISkyrimMod patchMod
        )
        {
            Dictionary<String, LandscapeTexture> cleanedLandscapeTextures = new Dictionary<String, LandscapeTexture>();
            foreach (var landscapeTexture in Settings.Value.TexturesToClean)
            {
                // Search for original version of landscape texture
                if (!loadOrderLinkCache.TryResolve<ILandscapeTextureGetter>(landscapeTexture, out var landscapeTextureRecord) || landscapeTextureRecord.EditorID is null)
                {
                    Console.Error.WriteLine($"Cannot find landscape texture record '{landscapeTexture}'");
                    continue;
                }

                // Duplicate it
                var newLandscapeTextureRecord = patchMod.LandscapeTextures.DuplicateInAsNewRecord(landscapeTextureRecord);
                newLandscapeTextureRecord.EditorID = "NR_NoGrass_" + newLandscapeTextureRecord.EditorID;

                // Remove the grass
                newLandscapeTextureRecord.Grasses.Clear();

                cleanedLandscapeTextures.Add(landscapeTextureRecord.EditorID, newLandscapeTextureRecord);
            };

            return cleanedLandscapeTextures;
        }
    }
}
